### PR TITLE
Release v0.1.0

### PR DESCRIPTION
**Pull request by YuiKasagi**
I have corrected the information in `README.md`, `setup.py` and `getstarted.rst` for release v0.1.0 in my last commit.
(By the way, is the version numbering appropriate?)

### CODE REVIEW

**Comment by HajimeKawahara** [comment]
Confirmed that all of the unit tests passed in my environment.

**Review by HajimeKawahara — COMMENTED** [review]
Should we remove the part for making figures in image_aptrace.py (because it's a unit test)?

**Review by HajimeKawahara — APPROVED** [review]

**Review by kemasuda — APPROVED** [review]
All the tests worked in my environment, but in test_stream2d.py it'd be useful if the directory paths could be modified following https://github.com/prvjapan/pyird/pull/42#discussion_r875404304

**Comment by YuiKasagi** [comment]
Thank you for your comments! I revised some codes to reflect comments. (1. do not output the figure for test_aptrace.py, 2. change the way to write paths by using .expanduser().)

**Pull request merged**
