### PR TITLE
modules for plotting interactive images 

### PR DESCRIPTION
**Pull request by YuiKasagi**
I made `pyird/utils/image_widget.py` which can show interactive images on new windows.
How to use it is demonstrated in `example/python/check_1Dto2D.py`.

On a window like in the following figure, you can zoom up on the image and check the location on the detector by pressing any key on the spectrum shown at the top.
スクリーンショット 2022-11-17 13 23 25

### CODE REVIEW

**Comment by HajimeKawahara** [comment]
It ended up this error...

```sh
shirochan:~/pyird(feature/show_1D2Dimage)>python examples/python/check_1Dto2D.py 
No fitsid yet.
h  band
100%|██████████████████████████████████████████████████████████████████████████████████| 50/50 [00:00<00:00, 421.92it/s]
cross-section: row  1170
100%|███████████████████████████████████████████████████████████████████████████████████| 42/42 [00:26<00:00,  1.60it/s]
100%|███████████████████████████████████████████████████████████████████████████████████| 42/42 [00:00<00:00, 63.38it/s]
fitsid: [43814]
/home/kawahara/pyird/data/20210317/dark/IRDA00043814.fits does not exist.
If you wanna proceed despite this warning, set self.not_ignore_warning = False in your fitsset.
Error.
```

**Comment by YuiKasagi** [comment]
Please download IRDA00043814 and 43815 from the following link.
[https://drive.google.com/drive/folders/1ccYM-dF41UgYv9fVHyGQp5m98wQEgOdY?usp=sharing](url)

**Review by kemasuda — APPROVED** [review]
I ran check_1Dto2D.py on an intel iMac. The windows showing orders 10 and 12 were shown and I was able to locate the peaks in the 1d spectra on the detector plane. All the unit tests also worked.
image_order12
image_order10

**Comment by HajimeKawahara** [comment]
Cool features! Ubuntu 20.04 Python 3.8.8

hotpixel

**Comment by HajimeKawahara** [comment]
My suggestions are
- put a mark on the spectrum window same as the detector window.
- if possible, change the color or mark type, for each click
- some explanation on the title? I needed some time to understand how to use it

Thanks for the cool feature.

**Review by HajimeKawahara — APPROVED** [review]

**Comment by YuiKasagi** [comment]
I have updated some features. Thank you for your suggestions!!
I will merge this here but will update it if there are other issues or suggestions.

スクリーンショット 2022-11-19 11 50 54

**Pull request merged**
