### PR TITLE
IRD stream (ver.2; wavelength calibrated 1d spectrum)

### PR DESCRIPTION
**Pull request by YuiKasagi**
The assignment of wavelength to the extracted 1D spectrum is implemented in `IRD_stream.py`.
It will be saved as a text file named "w?????_m2.dat." ($1: wavelength, $2: order, $3: flux (ADU))

In the next update (ver.3), I'm going to add functions to normalize the 1D spectrum by the blaze function. #38

### CODE REVIEW

**Review by HajimeKawahara — APPROVED** [review]
Thanks! I confirmed that this PR worked in my environment.

**Comment by HajimeKawahara** [comment]
Added @kemasuda as one of the regular reviewers :stuck_out_tongue:

**Comment by HajimeKawahara** [comment]
The data are [here](http://exoplanets.sakura.ne.jp/pyird/data/).

**Review by kemasuda — APPROVED** [review]
The PR worked in my environment as well, but test_getinfo.py failed; see issues.

**Comment by HajimeKawahara** [comment]
Thanks!

**Pull request merged**
