### PR TITLE
removed nan values in the RN model and optimized aperture widths

### PR DESCRIPTION
**Pull request by YuiKasagi**
This PR fixes a bug: there sometimes appears flux=0 in a spectrum

e.g.)
スクリーンショット 2023-07-27 10 00 58

### Causes
- I found that flux=0 regions were related to remaining nan values in the readout noise model.
- Those nans result from failed modeling. (Especially in the part where make median model. It is partially due to too wide aperture widths.)

### Changes
- Pad nan values with the model which is combined with the medians taken along X and Y axis respectively.
- Optimized aperture widths. New widths (6 pix for IRD) are consistent with Hirano-san's reduction process.
(I confirmed that the previous aperture widths were too broad (previous: 10 pix in YJ band) and amplified the noise in YJ band. The above change may solve the large noise in YJ band #68)

### CODE REVIEW

**Comment by YuiKasagi** [comment]
If you have time, it would be helpful if you could review this. @ZiyingGu

**Comment by ZiyingGu** [comment]
I have checked the old method: flat.dispcor(master_path=thar.anadir, blaze=False).
And it works welll.
Zero values are removed effeciently.

(blue is original)
image

**Review by HajimeKawahara — APPROVED** [review]
Thanks! great work.

**Comment by ZiyingGu** [comment]
I have confirmed it works well for both old and new ways.

old:
flat.dispcor(master_path=thar.anadir, blaze=False)

new:
flat_star.flatten(hotpix_mask=hotpix_mask)
df_flatn = flat_star.apnormalize()

image

**Pull request merged**
