### PR TITLE
Release v0.3.0

### PR DESCRIPTION
**Pull request by YuiKasagi**
Release branch for ver. 0.3.0

Any comments and reviews are welcome!
(note: I think the accuracy of the reduction of this ver. is comparable to that of IRAF.)

### CODE REVIEW

**Comment by HajimeKawahara** [comment]
Can you briefly explain the difference in v0.3 from 0.2? @YuiKasagi

**Comment by YuiKasagi** [comment]
### Changes v0.2 -> v0.3
- [Fixed & New] Update Hotpix mask to a more accurate one and add an option to read a prepared mask.
- [New] Interactive figures for 1D spectrum and 2D detector image
- Fixed bugs for making order combined spectrum
- Fixed bugs of `clean pattern` -> slightly improves the accuracy of clean pattern

**Review by HajimeKawahara — APPROVED** [review]
Thanks. The doc is [here](http://secondearths.sakura.ne.jp/pyird/).

**Comment by kemasuda** [comment]
I reduced IRD/REACH spectra using v0.3.0 and compared the results with those reduced with an older version. Overall I found a good agreement and hot pixels appear to be better removed in the new version. On the other hand, I noticed that the accuracy of wavelength calibration might've slightly worsened especially in the orders near the edge; in the order shown below, the new reduction yields longer/shorter wavelengths at the shortest/longest wavelength regions in the order.
42313_H_order1
I think this issue has already been known, and the difference from the previous reduction is smaller in other regions (e.g. order 10 below). So if this is not something that can be easily fixed it may be fine to go with this version but I thought I'd anyway share this in case it's useful for future improvements.
42313_H_order10

**Review by kemasuda — APPROVED** [review]

**Comment by YuiKasagi** [comment]
Thank you for reviewing!

After reading Masuda-san's comment, I am re-checking the identification process of ThAr lines. And there seems to be something wrong in this process of v0.3.0, so I will merge after fixing this problem.

**Comment by YuiKasagi** [comment]
I wrote "something wrong" in above comment, but I confirmed v0.3.0 worked correctly.
I don't think this version would significantly worsen wavelength calibration accuracy, so I will merge it here.

The following are reasons for the conclusion and a report↓
I found that the wavelength differences were caused by:
the noise levels of the ThAr spectrum reduced with new `clean_pattern` are different from the old version 
→ the detected ThAr emission lines changed, and lines used for the calibration were also slightly different
→ wavelengths changed (<10pix) 

One solution is to change the variable of `stdlim` of `utils.irdstream.calibrate_wavelength`, which is the value of the std until which the function rejects ThAr lines used for calibration. I tried to change that value (e.g. `stdlim=0.0009`; default is 0.001), however, there was any significant changes in the wavelengths. 
Also, the differences of the wavelengths from IRAF reduction are almost the same for both v0.2 and v0.3.

**Comment by kemasuda** [comment]
Thanks a lot for looking into this! It's really nice to know what was likely causing the difference. I'll also try tweaking the stdlim parameter.

**Pull request merged**
