### PR TITLE
Correct the wavelength grid when combining the flux of adjacent orders

### PR DESCRIPTION
**Pull request by YuiKasagi**
I think this can fix the problem of issue #65 

I have changed the order of the code for the part that limits wavelengths.

### CODE REVIEW

**Comment by YuiKasagi** [comment]
Can I add @ZiyingGu as a reviewer?

**Review by HajimeKawahara — APPROVED** [review]

**Comment by HajimeKawahara** [comment]
I invited @ZiyingGu as a prvjapan member. After accepting the inivitation, Gu-san can be a reviewer.

**Comment by ZiyingGu** [comment]
Thank you for your inviting!😁

**Review by ZiyingGu — APPROVED** [review]
This problem is fixed successfully. Thank you!

**Pull request merged**
