### PR TITLE
Add a new class Stream1D and the function for fringe removal in REACH spectrum

### PR DESCRIPTION
**Pull request by YuiKasagi**
### Summary of new features

- Create a new class `Stream1D` (preliminary) (with reference to Stream2D)
- Additional output nwflat_?_m?.dat from Stream2D
- Add functions for fringe removal in REACH spectrum (output is rfnw***_*_?.dat)
- **demo: please try `REACH_stream.py`, then `REACH_stream1D.py`** You will get the fringe removed spectrum like in the bottom figure. (Once you get outputs from Stream2D, it is ok just running the latter code.)

### Overview of the concept of `irdstream`

See also #69 
- Important outputs from Stream2D: w***_m?.dat, nw***_m?.dat, wflat_?_m?.dat, nwflat_?_m?.dat (<-- new!!)
    - prefix='w': wavelength calibrated spectrum
    - prefix='nw': wavelength calibrated and normalized spectrum
- Output(s) from Stream1D: rfnw***_*_?_m?.dat (from `remove_fringe()`)
    - more functions will be added to Stream1D

#### What is done in `remove_fringe()`
- Input: wavelength calibrated and normalized flat spectrum & target spectram 
- multiple frames  can be accepted for target, in that case, they are used after the median combine
- Based on the periodic noise in flat spectrum,  the noise with those frequencies in target spectrum will be subtracted 
- Images compare the spectrum before/after and their periodogram. You can see the periodic noise in the target spectrum is reduced.

remove_fringe_demo1
remove_fringe_demo2

### CODE REVIEW

**Review by HajimeKawahara — COMMENTED** [review]
Thanks! Just a question. 
I did not understand the format of "dat", i.e. DatSet. 
Checking [this line](https://github.com/prvjapan/pyird/blob/b546262179c6d77d3b0f407db3c3d88a03430d8e/src/pyird/utils/irdstream.py#L671), I understand "dat" means .to_csv(sep=" "). 
But is there any reason to use this specific format as an output?
If no reason, csv (sep=",") is more user-friendly? CsvSet?

**Comment by YuiKasagi** [comment]
> But is there any reason to use this specific format as an output?
> If no reason, csv (sep=",") is more user-friendly? CsvSet?

Thank you for pointing it out. 
This 'dat' format just follows the previous (Hirano-san's) pipeline. The merit of this format is that it is easy to use outputs for his RV measurement codes, including more precise wavelength calibration with comb spectra.
I agree that it would be easy to deal with csv format (with column name?) for pyird users and also for me (used to pandas).
...Which plan do you think is best?

A) change outputs of pyird to csv format, and implement wavelength calibration with comb spectrum to pyird (I think it will take time...)
B) change outputs of pyird to csv format, and implement a function to convert csv to dat
C) still use dat

**Comment by HajimeKawahara** [comment]
I see. Thanks. For instance, why not allow users to choose the sep option?

**Comment by YuiKasagi** [comment]
Sounds good. I will add the sep option.

**Review by HajimeKawahara — APPROVED** [review]
Thanks!

**Review by kemasuda — APPROVED** [review]
Sorry that I was missing this pull request. I tried running REACH_stream1D.py and confirmed that rfnwHR37635_20211110_h_m2 was produced successfully.

**Pull request merged**
